---
driver:
  name: vagrant
  synced_folders:
    - ['pkg', '/opt/kitchen_test/extract']

provisioner:
  name: chef_solo

platforms:
  - name: boxcutter/centos72
  - name: windows-7
    box: win7-64
    driver:
      gui: true
      customize:
        memory: 4096

suites:
  - name: extract
    run_list:
      - recipe[zipfile_test::extract]
    attributes:
      extract:
        from: /opt/kitchen_test/extract/to_extract.zip
        into: /tmp/to_extract
