---
driver:
  name: vagrant
  synced_folders:
    - ['pkg', '/opt/kitchen_test/extract']

provisioner:
  name: chef_solo

platforms:
  - name: centos
    driver:
      box: boxcutter/centos72
  - name: windows
    driver:
      box: devopsgroup-io/windows_server-2012r2-standard-amd64-nocm
      communicator: winrm
      customize:
        memory: 4096

suites:
  - name: extract
    run_list:
      - recipe[zipfile_test::extract]
    attributes:
      extract:
        from: /opt/kitchen_test/extract/to_extract.zip
        into: /tmp/to_extract
      overwrite:
        from: /opt/kitchen_test/extract/to_extract.zip
        into: /tmp/to_extract_overwrite
      nonexistent_into:
        from: /opt/kitchen_test/extract/to_extract.zip
        into: /tmp/into/nonexistent_parent/a/b/c/d/e/f
